[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking = "644vqVe3YkkDsmb7tGkstkJ1HxG31tYN1KQEXsDv1tWW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
